### ISSUE TITLE
Build and Upload Version 3.10 to F-Droid

### ISSUE THREAD

**Issue by landry314** [slp/Telegram-FOSS#102]
Version 3.11 of Telegram for Android was just released!

https://play.google.com/store/apps/details?id=org.telegram.messenger

https://github.com/DrKLO/Telegram

**Comment by mg-13** [comment]
The original code for 3.10 is not even online yet, you have to wait a bit longer

https://github.com/DrKLO/Telegram/commits/master

**Comment by vanitasvitae** [comment]
Now it is. Looking forward to a new release :)

**Comment by SkyWheel** [comment]
It would be nice to have the new version to build an apk.

**Comment by landry314** [comment]
version 3.11 was just released on the play store. i am editing the title of this issue instead of having it be closed. maybe that is bad form but im doing it!

**Comment by mg-13** [comment]
again, no source code for 3.11
is there anyone working on updating Telegram-FOSS at all?
I'm not familiar with the project, neither do I have an Android dev environment set up

**Comment by Peque** [comment]
@landry314 I don't think that is a good idea. This issue was created for version 3.10, and it was successfully solved/fixed. If there is a new issue now (i.e.: updating to 3.11), I think you should create a separate thread instead for discussion and updates on that matter.

@mg-13 As you can see, mostly there is @slp and @Bubu. I do not think they are *working* on this (not getting payed for it), simply dedicating some of their free/spare time when they can/want. :wink:

**Comment by slp** [comment]
Telegram-FOSS 3.10.1 is already available on F-Droid.
