### ISSUE TITLE
Source code of version 3.13.1 available

### ISSUE THREAD

**Issue by thilo-dual** [slp/Telegram-FOSS#118]
The source code was pushed to https://github.com/DrKLO/Telegram just yesterday :)

**Comment by slp** [comment]
Thanks. I've just merged the changes, and I'm working on fixing stuff. It'll take a few days.

**Comment by Salkin2** [comment]
I see here: https://github.com/slp/Telegram-FOSS that it's updated to the version 3.13 three weeks ago, but where can we download it? It isn't published on F-droid, :-/ Could you please provide the link with the APK?

**Comment by slp** [comment]
I've just finished merging the changes and fixing the usual problems. Version 3.13.1 is tagged and ready. It also includes a fix for the longstanding crash-on-share bug, and a new set of EmojiOne+Twemoji emojis, thanks to @thermatk.

As usual, it should be available on F-Droid in a few days.

**Comment by Salkin2** [comment]
@slp I thought it was ready almost a month ago. In the main page, https://github.com/slp/Telegram-FOSS, we can read a line that says "Update to 3.13.1 [...] 26 days ago". Should we not trust those messages?
Also, version 3.13.1 was published in Gplay a month ago, is there anything that users without programming skills could contribute to help Telegram FOSS developers to reduce these big delays, something that could relief a bit your work and speed the TG FOSS release cycle?

**Comment by monojp** [comment]
@Salkin2 that was just the big release commit that got merged from upstream. But because upstream releases its source only once in a while as a big bundle, the contributors of Telegramm-FOSS have to go through all the changes and fix things that only are working with proprietary Google Services and stuff like that. Sometimes these fixes are just a few smaller things that got broken while merging, sometimes features have to be removed and sometimes things need to be completely rewritten which takes of courese time.
After that there is also the testing process and only after everything or at least the build is finally working it can be tagged and released for f-droid.
If you look at the recent commits you can see that @slp has made those fixes for release in the last few days. And you can't really compare the releases here to Google Play because upstream is so slow with updating the source code..

**Comment by Peque** [comment]
@slp The new update works great for me so far: no crashes on sharing images, Telegram game-bots... Thanks for your work! :heart:

**Comment by Bubu** [comment]
Thanks a lot @slp. It's now online on fdroid. Closing.

**Comment by thermatk** [comment]
Play Store is on 3.13.2 since the 4th, but no source code yet :(

**Comment by Salkin2** [comment]
@monojp Thanks for ilustrating my disknowledge :)
Could we, the common users help in some way, I dont know... testing perhaps, trying to press upstream to publish the code at the same time they publish a new versioned APK (this is how OSS software usually works, right?)... whatever, to speed up a little the process?

**Comment by Bubu** [comment]
"trying to press upstream to publish the code at the same time they publish a new versioned APK"
This is always a good idea! :-)
