### ISSUE TITLE
Can't share GIF to other apps

### ISSUE THREAD

**Issue by Salkin2** [slp/Telegram-FOSS#120]
When I try to share a GIF animation Telegram converts it to a video file instead of sharing it as the original GIF. This ruins the advantage of animated GIF, that is inline play in mails, social networks, other messengers, etc.
Could that video conversion annoyance be removed, or at least make it optional?

Regards.

**Comment by Bubu** [comment]
I think Telegram converts the gifs to videos because videos are much more efficent regarding disk space and playback performance. I would reckon it doesn't save the original gifs. But I don't actually know.

Anyway, this is not the place to ask for such changes, maybe this is even a server side feature(?).\
Please contact Telegram support.

**Comment by Salkin2** [comment]
Didn't know videos occupied less disk space, good to know it. But about playback performance... I don't think I agree: if you have to launch a video player externally instead playing a GIF inside the app you need extra resources to execute the video player, and you also lose more time, which in mobiles means also more power comsumption.

I thought it was the application what did the conversion to mp4, that's why I thought this was an appropriate place to ask, sorry. So, you are sure I should contact TG support instead?

**Comment by Bubu** [comment]
I don't know where the conversion takes place, sorry. But that's not really the point. We can't change such a thing here, because it's not the scope of the project. And I guess it work fine for 'most' users.

Also the videos should play inline in Telegram, no need to open a 3rd party video player. (Otherwise this would indeed be very inconvenient.)
