### ISSUE TITLE
Notifications only if the application is running

### ISSUE THREAD

**Issue by Eibriel** [slp/Telegram-FOSS#28]
Hi! I'm not getting notifications if the application is closed.
Android 4.4.2 on Acer Iconia with Intel Atom.
When I touch the telegram icon to open it I received all the notification at once.
Version 2.5.2 from f-droid

**Comment by TameOfGroans** [comment]
click task switching soft key

long click app

app info


is "show notifications" ticked?

**Comment by Eibriel** [comment]
Hi, yes.
I'm running Android 4.4.2 kernel 3.10.20, CPU Intel Atom on a Tablet Acer.

**Comment by slp** [comment]
Try going to "Settings->Notifications and Sounds" and select "Reset All Notifications".

**Comment by muava12** [comment]
@Eibriel have you tried the newest version?, i have the same problem and solved with v2.8

**Comment by mcagl** [comment]
Some months ago I had a similar problem: I received telegram notifications as I picked up the phone and turned the screen on (issue I had only for telegram. All other applications gave me the notifications regularly).

Then with some update the problem was gone. Now it's since some weeks (maybe more) that I experience the same issue: when the phone is in standby no notifications, and it's annoying to have to wake up the screen from time to time just to make telegram notify my messages that can be sent hours before.

For my use case it seems like a regression.

Huawei Y300 - Telegram v2.9.1 (542) from fdroid. (and yes, i have active notifications in the app, notification service on in the settings, etcetera)

**Comment by 9peppe** [comment]
I think it happens because notifications, in nonFOSS Telegram, are handed by GMS in google services. Check if the Telegram internal notification system is on: Sidebar -> Settings -> Notifications and Sound -> Notifications Service (the topmost switch).

**Comment by Ecron** [comment]
@9peppe That's not true. In official Telegram app the Notifications are handled by their own Notification System, and it's active by default [Sidebar -> Settings -> Notifications and Sound -> Notifications Service (the topmost switch), as you said]. As this FOSS app is not relying in GMS, Telegram's Notification system should be always ON. In fact, if you deactivate that option, you shouldn't be able to receive any notification at all. Wouldn't be useful to delete that option from Notification and Sound settings?

**Comment by slp** [comment]
Let's track this issue at #36
