### ISSUE TITLE
Compatibility with older Android versions

### ISSUE THREAD

**Issue by Lesik** [slp/Telegram-FOSS#49]
I just noticed in the [stock emoji commit](https://github.com/slp/Telegram-FOSS/commit/03771b0cb2a4f18486c66887466551d424e4c9c0?diff=unified#diff-3700629783fb7209df0b9e49538cd538L80) that the lowest Android SDK was raised to 10 (Android 2.3.3). It's not such a big problem, but still a problem. [According to Google](https://developer.android.com/about/dashboards/index.html) these are <4% of all Android devices, but keep in mind that Google only counts the devices that have Google Play Services installed. Before the ICS era many (Chinese) manufacturers flooded the market with cheap phones which have not been certified for Google Play Services and thus are not counted in this statistic. The users of these devices rely on third-party stores like F-Droid (as they're not certified to use the Play Store), which contain Telegram versions like this one. Just to keep in mind.

I agree that Gingerbread 2.2.3 (API 10) is already pretty low. But I hope we can maintain this project to be usable for everybody, everywhere.

Thoughts?

**Comment by Ecron** [comment]
Mmmmm... That's a tough topic. Telegram will drop support to Android < 4.X in the future, for sure, because there are some new features hard to keep with such old SDK. That's a pity, because even I'm using currently Gingerbread, but that's a fact that will become reality sooner or later.

Maintaining this project with such compatibility... It'd be ideal, but will be hard to accomplish.

**Comment by slp** [comment]
Raising the SDK to 10 was a requirement of TextDrawable. I'll check if that project really requires that version, or it can be easily lowered.

**Comment by slp** [comment]
On recent Telegram (upstream) versions, the minimal API requirement has been further increased. There's nothing we can do.
