### ISSUE TITLE
Battery Drain on no Data connectivity

### ISSUE THREAD

**Issue by NeroBurner** [slp/Telegram-FOSS#68]
Telegram Version 3.3.1 from FDroid
Screenshots of stats taken with com.askseven.betterbatterystats version 1.15.0.0 from FDroid

Test-Setup:
Unplug Phone, deactivate Wifi and Data Connectivity, sleep 8 hours, wake up, take screenshot

The first screenshot is with Telegram installed. There were 4482 Wakeups because of telegram, whatsapp only had 11. My Battery went from 70% to 50%

![screenshot_2016-01-21-07-22-11](https://cloud.githubusercontent.com/assets/9076163/12505006/4532a50c-c0e3-11e5-8bda-37e4603ab7f2.png)

Next night I uninstalled telegram and again deactivated all data connectivity. I started with 76% battery, and in the morning I couldn't believe my eyes: I still had 76% battery!
![screenshot_2016-01-22-07-18-10](https://cloud.githubusercontent.com/assets/9076163/12505007/45381db6-c0e3-11e5-87b0-0bd0a4ccfbe0.png)

Another screenshot of the second night. I charged my phone for a few minutes before going to bed
![screenshot_2016-01-22-07-17-53](https://cloud.githubusercontent.com/assets/9076163/12505079/e6e1106e-c0e3-11e5-983e-9489b746177e.png)

Is there a way to deactivate the Wakeups when there is no data connectivity at all?

**Comment by Akronix** [comment]
Duplicated of #59.

**Comment by Bubu** [comment]
@slp Can we do anything to disable the alarm service when there is no data connectivity? And then re-enable it when the phone goes online again?

**Comment by slp** [comment]
@bubu I've just commited a change which:
 - For Android-SDK < 19, uses Alarm.set instead of Alarm.setRepeating (probably, the cause of this problem).
 - Implements a simpler repeating Alarm, and allows the user to switch to it with the preference option "NotificationsService" ("pushService" internally), now renamed as "Smart Push" (without localization, I don't think is worth the effort).

For some Phone/AndroidSDK combinations, Smart Push will work better. For others, the repeating Alarm is more reliable. There's no way to autodetect this, so let the user choose.

BTW, with this change, there's no option to disable the Notifications Service itself, but I don't think that makes any sense.

Please take a look at the changes, and if you fell comfortable with them, create (and push) tag v3.4.2

Thanks!

**Comment by Bubu** [comment]
@slp So 'smart push' = on is what was implemented for the last version, right?

Looks good so far. I just got BetterBatteryStats working on my Phone and will test if it makes any difference on my device. (CM 12.1)
Right now I too get 2-3 wakeups /min even in aeroplane mode.

**Comment by slp** [comment]
@bubu Yup, smart push is the what we had 3.3.1.

I though the culprit was setRepeating, but you're right, JNI's code is so dumb it still tries to maintain the socket when there's no network connection. I don't want to fiddle with that code too much, but I've just added a quick check to avoid setting the alarm when networkAvailable == false.

This change will have to wait for next release, though.

**Comment by Bubu** [comment]
@slp Sounds good!
What happens when the network comes back? Will notifications resume automatically?

**Comment by Bubu** [comment]
Does this check also work with the dumb 1/min alarm?

**Comment by NeroBurner** [comment]
Tried with the new telegram version over 2 nights. I deactivated all data connectivity (Wifi and Wireless) over the night 

smart push:
    duration: 9 hours
    wakelocks: 4773 (approx 530/hour)
    battery: from 72% to 52% (approx 2.2%/h)
    
dumb push:
    duration: 8 hours
    wakelocks: 478 (approx 60/hour)
    battery: from 78% to 73% (approx 0.6%/h)

**Comment by slp** [comment]
Smart Push should be somewhat better on next release. We can also consider disabling it by default.

**Comment by NeroBurner** [comment]
Can you elaborate what better means? What strategy will smart push have that makes it better?

Also would it be possible to release (development) versions on fdroid between official releases? For example 3.4.2-1. I think there is a way to mark them beta or something on fdroid so those releases are not marked as updates by default

**Comment by beljebuzz** [comment]
Ok, lets say it first: I have no idea how to program a network application for Android. Excuse me if my suggestion is stupid in this context, but please never consider it an offense: why not to attach a network status monitor and start/stop alarms/pushing based on the reported status?

http://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html

**Comment by slp** [comment]
On 3.10.x, NetworkAlarm has been replaced with a simpler repeating Alarm.
