### ISSUE TITLE
Notifications of secret chats doesnt show the content of the new message

### ISSUE THREAD

**Issue by Imarok** [slp/Telegram-FOSS#77]
The "New Message Notification" of a secret chat doesnt show the content of a message it just says: "You have a new message"

**Comment by Bubu** [comment]
I think that's intentional so that the message preview will not be shown on the lockscreen.
But I agree it is handled poorly, it could very well be shown when the phone is unlocked. There could be technical reasons, such that the message is not yet decrypted when the notification is showing, before entering the corresponding chat.

Anyway, there are no code changes in this version from upstream in this part of the code, so you should report the problem to their [support](https://telegram.org/support). 
But maybe wait until the next version is released, it might have changed there, they did some stuff with the secret chats.
