### ISSUE TITLE
No in-App Changelog shown on version update.

### ISSUE THREAD

**Issue by Bubu** [slp/Telegram-FOSS#79]
Since the 3.6.1 update Telegram should get the Changelog on app update from the remote Server.  This apparently doesn't work in our version for reasons I don't yet understand. (see [here](https://github.com/slp/Telegram-FOSS/blob/8d74a3425dafa305ba1b9c82b93725b4ddb86aa1/TMessagesProj/src/main/java/org/telegram/messenger/MessagesController.java#L3884))

Maybe it only works with official Telegram apps but I couldn't find anything regarding this in the code.

As a workaround I created a [Changelog file](https://github.com/slp/Telegram-FOSS/blob/HEAD/Changelog.md) in the repository and linked it from fdroid.

**Comment by aphirst** [comment]
Strange that this behaviour would change, I'm sure I remember that this used to work.

**Comment by Bubu** [comment]
Telegram used a hard coded version update string up to the last version which just listed all the changes client side.
So this definitely changed in the code.

**Comment by Ecron** [comment]
Since version 3.5, Telegram for Android won't send the changelog message client-side, but in a server-side way. I noticed it some weeks ago, when translating official app (the string regarding updates didn't got updated to latest version).

Maybe if 3rd-party developers made an official request to Telegram Team, they would consider reverting this behaviour to previous one.

This decision is also negative for those countries with more than one official language (see Spain, Belgium, etc). The message was previously displayed in the app's language, if it was up to date. Now it is served in a coutry-prefix basis.

I sent myself the corresponding complaints as a user, but I insist, maybe 3rd-party devs could join and send formal complaints.

**Comment by Bubu** [comment]
I don't think we will be getting this back. If nobody wants to integrate a new changelog system for us we just have to keep updating our [Changelog.md](https://github.com/slp/Telegram-FOSS/blob/master/Changelog.md) file.

Clsoing this. If someone is interested in working on this, go ahead :-).
