### ISSUE TITLE
Update to 3.7

### ISSUE THREAD

**Issue by Bubu** [slp/Telegram-FOSS#86]
No code available yet.

**Comment by Teleg** [comment]
Code is online:

https://github.com/DrKLO/Telegram/commit/a7513b3ba1923113840e78799c4c4132cc7f3116

**Comment by opensrc1229** [comment]
Any problems with version 3.7? I ask this because its release was 12 days ago.

**Comment by slp** [comment]
I'm on it.

**Comment by aphirst** [comment]
@opensrc1229 It often takes a little time to work out a) what on earth was actually changed since the last version (the upstream repo tends to make one colossal commit per version which must be a nightmare), and in most cases b) make some modifications based on the things that Telegram-FOSS either re-implements, cleans up (both code and software-licensing...), or removes. We'll all have it when it's ready. :smile:

**Comment by Bubu** [comment]
@opensrc1229 In this particular case the gradle build changed somewhat and I didn't have any time to test the changes for fdroid until now.

**Comment by slp** [comment]
I've just tagged version 3.7.0. It will be soon available on F-Droid.

**Comment by Bubu** [comment]
@slp Thanks for you work!

**Comment by opensrc1229** [comment]
I didn't want to push with posting my question. You are doing a good job, thanks!
